language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
