version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: chmod +x ./gradlew
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew check --stacktrace
      - run: ./gradlew jacocoTestReport

      - run: "[[ -n ${SIGNING_KEY_SECRING_BASE64} ]]"
      - run: echo $SIGNING_KEY_SECRING_BASE64 | base64 --decode > ./signing.key.secring
      - run: export SIGNING_KEY_PATH=./signing.key.secring
      - run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -DDEPLOYMENT=true

      - run: mkdir -p projectpage
      - run: cp -rv build/reports/* projectpage
      - run: cp -rv build/docs/* projectpage
      - run: cp -rv docs/* projectpage
      # force push to the repo gh-pages branch

  build:
    docker:
      - image: cimg/openjdk:11.0
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: chmod +x ./gradlew
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew check --stacktrace

workflows:
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy:
          filters:
            tags:
              # any tag
              only: /.*/
            branches:
              # no branches
              ignore: /.*/

  build-workflow:
    jobs:
      - build:
          filters:
            tags:
              # not tag
              ignore: /.*/
